language: php
php:
  - 7.0
sudo: enabled
branches:
  only:
    develop
before_install:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev
script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php src/TestEmail.php
